# Generated by Django 5.2.4 on 2025-10-02 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expcoin',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expcoin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expcoin', to=settings.AUTH_USER_MODEL),
        ),
    ]
